

package vista;


public class Interfaz extends javax.swing.JFrame {


    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextFieldMatricula = new javax.swing.JTextField();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldGrupo = new javax.swing.JTextField();
        jTextFieldGeneracion = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nuevo = new javax.swing.JButton();
        insertar = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        actualizar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldApellidoPaterno = new javax.swing.JTextField();
        jTextFieldApellidoMaterno = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabelImagen = new javax.swing.JLabel();
        jTextFieldBuscar = new javax.swing.JTextField();
        jButtonBuscar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldID = new javax.swing.JTextField();
        jTextFieldBuscarRuta = new javax.swing.JTextField();
        jButtonBuscarRuta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 204));
        setName("Registro de alumnos"); // NOI18N

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 1, 1, new java.awt.Color(102, 51, 255)), "Registros"));
        jPanel1.setLayout(null);

        jTextFieldMatricula.setBackground(new java.awt.Color(0, 0, 0));
        jTextFieldMatricula.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jTextFieldMatricula.setForeground(new java.awt.Color(0, 204, 204));
        jTextFieldMatricula.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldMatricula.setBorder(null);
        jPanel1.add(jTextFieldMatricula);
        jTextFieldMatricula.setBounds(170, 350, 233, 30);

        jTextFieldNombre.setBackground(new java.awt.Color(0, 0, 0));
        jTextFieldNombre.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jTextFieldNombre.setForeground(new java.awt.Color(0, 204, 204));
        jTextFieldNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldNombre.setBorder(null);
        jPanel1.add(jTextFieldNombre);
        jTextFieldNombre.setBounds(170, 220, 233, 30);

        jTextFieldGrupo.setBackground(new java.awt.Color(0, 0, 0));
        jTextFieldGrupo.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jTextFieldGrupo.setForeground(new java.awt.Color(0, 204, 204));
        jTextFieldGrupo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldGrupo.setBorder(null);
        jPanel1.add(jTextFieldGrupo);
        jTextFieldGrupo.setBounds(170, 400, 233, 30);

        jTextFieldGeneracion.setBackground(new java.awt.Color(0, 0, 0));
        jTextFieldGeneracion.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jTextFieldGeneracion.setForeground(new java.awt.Color(0, 204, 204));
        jTextFieldGeneracion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldGeneracion.setBorder(null);
        jPanel1.add(jTextFieldGeneracion);
        jTextFieldGeneracion.setBounds(170, 440, 233, 30);

        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Matricula");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(40, 350, 60, 15);

        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Nombre");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 220, 37, 15);

        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Grupo");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 400, 50, 15);

        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Generación");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(40, 440, 70, 15);

        nuevo.setText("Nuevo");
        jPanel1.add(nuevo);
        nuevo.setBounds(30, 500, 79, 25);

        insertar.setText("Insertar");
        jPanel1.add(insertar);
        insertar.setBounds(130, 500, 79, 25);

        eliminar.setText("Eliminar");
        jPanel1.add(eliminar);
        eliminar.setBounds(230, 500, 83, 25);

        actualizar.setText("Actualizar");
        jPanel1.add(actualizar);
        actualizar.setBounds(330, 500, 83, 25);

        jLabel5.setBackground(new java.awt.Color(102, 102, 102));
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Apellido Paterno");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(40, 270, 110, 15);

        jLabel6.setBackground(new java.awt.Color(102, 102, 102));
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Apellido Materno");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(40, 310, 110, 15);

        jTextFieldApellidoPaterno.setBackground(new java.awt.Color(0, 0, 0));
        jTextFieldApellidoPaterno.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jTextFieldApellidoPaterno.setForeground(new java.awt.Color(0, 204, 204));
        jTextFieldApellidoPaterno.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldApellidoPaterno.setBorder(null);
        jPanel1.add(jTextFieldApellidoPaterno);
        jTextFieldApellidoPaterno.setBounds(170, 270, 233, 30);

        jTextFieldApellidoMaterno.setBackground(new java.awt.Color(0, 0, 0));
        jTextFieldApellidoMaterno.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jTextFieldApellidoMaterno.setForeground(new java.awt.Color(0, 204, 204));
        jTextFieldApellidoMaterno.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldApellidoMaterno.setBorder(null);
        jPanel1.add(jTextFieldApellidoMaterno);
        jTextFieldApellidoMaterno.setBounds(170, 310, 233, 30);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelImagen, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelImagen, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(430, 170, 300, 300);

        jTextFieldBuscar.setBackground(new java.awt.Color(0, 0, 0));
        jTextFieldBuscar.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jTextFieldBuscar.setForeground(new java.awt.Color(0, 204, 204));
        jTextFieldBuscar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldBuscar.setBorder(null);
        jPanel1.add(jTextFieldBuscar);
        jTextFieldBuscar.setBounds(20, 30, 240, 30);

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonBuscar);
        jButtonBuscar.setBounds(270, 30, 90, 30);

        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("ID");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(40, 180, 30, 10);

        jTextFieldID.setBackground(new java.awt.Color(0, 0, 0));
        jTextFieldID.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jTextFieldID.setForeground(new java.awt.Color(0, 204, 204));
        jTextFieldID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldID.setBorder(null);
        jTextFieldID.setEnabled(false);
        jPanel1.add(jTextFieldID);
        jTextFieldID.setBounds(170, 170, 230, 30);
        jPanel1.add(jTextFieldBuscarRuta);
        jTextFieldBuscarRuta.setBounds(20, 70, 450, 30);

        jButtonBuscarRuta.setText("Search");
        jPanel1.add(jButtonBuscarRuta);
        jButtonBuscarRuta.setBounds(490, 70, 90, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton actualizar;
    public javax.swing.JButton eliminar;
    public javax.swing.JButton insertar;
    public javax.swing.JButton jButtonBuscar;
    public javax.swing.JButton jButtonBuscarRuta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabelImagen;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JTextField jTextFieldApellidoMaterno;
    public javax.swing.JTextField jTextFieldApellidoPaterno;
    public javax.swing.JTextField jTextFieldBuscar;
    public javax.swing.JTextField jTextFieldBuscarRuta;
    public javax.swing.JTextField jTextFieldGeneracion;
    public javax.swing.JTextField jTextFieldGrupo;
    public javax.swing.JTextField jTextFieldID;
    public javax.swing.JTextField jTextFieldMatricula;
    public javax.swing.JTextField jTextFieldNombre;
    public javax.swing.JButton nuevo;
    // End of variables declaration//GEN-END:variables
}
